// Generated by ProtoGen, Version=2.4.1.473, Culture=neutral, PublicKeyToken=55f7125234beb589.  DO NOT EDIT!
#pragma warning disable 1591, 0612
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace world_messages {
  
  namespace Proto {
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public static partial class WorldMessage {
    
      #region Extension registration
      public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
      }
      #endregion
      #region Static variables
      internal static pbd::MessageDescriptor internal__static_world_messages_MsgPlayerEnterRoom__Descriptor;
      internal static pb::FieldAccess.FieldAccessorTable<global::world_messages.MsgPlayerEnterRoom, global::world_messages.MsgPlayerEnterRoom.Builder> internal__static_world_messages_MsgPlayerEnterRoom__FieldAccessorTable;
      internal static pbd::MessageDescriptor internal__static_world_messages_MsgEnterRoomReply__Descriptor;
      internal static pb::FieldAccess.FieldAccessorTable<global::world_messages.MsgEnterRoomReply, global::world_messages.MsgEnterRoomReply.Builder> internal__static_world_messages_MsgEnterRoomReply__FieldAccessorTable;
      internal static pbd::MessageDescriptor internal__static_world_messages_WorldMessage__Descriptor;
      internal static pb::FieldAccess.FieldAccessorTable<global::world_messages.WorldMessage, global::world_messages.WorldMessage.Builder> internal__static_world_messages_WorldMessage__FieldAccessorTable;
      internal static pbd::MessageDescriptor internal__static_world_messages_Room__Descriptor;
      internal static pb::FieldAccess.FieldAccessorTable<global::world_messages.Room, global::world_messages.Room.Builder> internal__static_world_messages_Room__FieldAccessorTable;
      internal static pbd::MessageDescriptor internal__static_world_messages_ReplyMsg__Descriptor;
      internal static pb::FieldAccess.FieldAccessorTable<global::world_messages.ReplyMsg, global::world_messages.ReplyMsg.Builder> internal__static_world_messages_ReplyMsg__FieldAccessorTable;
      internal static pbd::MessageDescriptor internal__static_world_messages_MsgGetRoomListReply__Descriptor;
      internal static pb::FieldAccess.FieldAccessorTable<global::world_messages.MsgGetRoomListReply, global::world_messages.MsgGetRoomListReply.Builder> internal__static_world_messages_MsgGetRoomListReply__FieldAccessorTable;
      internal static pbd::MessageDescriptor internal__static_world_messages_MsgCreateRoomReply__Descriptor;
      internal static pb::FieldAccess.FieldAccessorTable<global::world_messages.MsgCreateRoomReply, global::world_messages.MsgCreateRoomReply.Builder> internal__static_world_messages_MsgCreateRoomReply__FieldAccessorTable;
      #endregion
      #region Descriptor
      public static pbd::FileDescriptor Descriptor {
        get { return descriptor; }
      }
      private static pbd::FileDescriptor descriptor;
      
      static WorldMessage() {
        byte[] descriptorData = global::System.Convert.FromBase64String(
            "ChJXb3JsZE1lc3NhZ2UucHJvdG8SDndvcmxkX21lc3NhZ2VzIjYKEk1zZ1Bs" + 
            "YXllckVudGVyUm9vbRIOCgZyb29tSWQYASACKAkSEAoIcGxheWVySWQYAiAC" + 
            "KAkiVQoRTXNnRW50ZXJSb29tUmVwbHkSDwoHcGxheWVycxgBIAMoCRIvCgZy" + 
            "ZXN1bHQYAiACKA4yHy53b3JsZF9tZXNzYWdlcy5FbnRlclJvb21SZXN1bHQi" + 
            "aAoMV29ybGRNZXNzYWdlEikKBHR5cGUYASACKA4yGy53b3JsZF9tZXNzYWdl" + 
            "cy5NZXNzYWdlVHlwZRIQCghwbGF5ZXJJZBgCIAIoCRIMCgRidWZmGAMgASgM" + 
            "Eg0KBW1zZ0lkGAQgAigFIjkKBFJvb20SCgoCaWQYASACKAkSEwoLcGxheWVy" + 
            "Q291bnQYAiACKAUSEAoIY2FwYWNpdHkYAyACKAUiUgoIUmVwbHlNc2cSKQoE" + 
            "dHlwZRgBIAIoDjIbLndvcmxkX21lc3NhZ2VzLk1lc3NhZ2VUeXBlEg0KBW1z" + 
            "Z0lkGAIgAigFEgwKBGJ1ZmYYAyACKAwiOgoTTXNnR2V0Um9vbUxpc3RSZXBs" + 
            "eRIjCgVyb29tcxgBIAMoCzIULndvcmxkX21lc3NhZ2VzLlJvb20iRQoSTXNn" + 
            "Q3JlYXRlUm9vbVJlcGx5EhEKCWVycm9yQ29kZRgBIAIoBRIKCgJpZBgCIAIo" + 
            "CRIQCghjYXBhY2l0eRgDIAIoBSqyAQoLTWVzc2FnZVR5cGUSDgoKQ3JlYXRl" + 
            "Um9vbRABEg0KCUVudGVyUm9vbRACEgwKCFF1aXRSb29tEAMSDwoLR2V0Um9v" + 
            "bUxpc3QQBBITCg9DcmVhdGVSb29tUmVwbHkQBRISCg5FbnRlclJvb21SZXBs" + 
            "eRAGEhEKDVF1aXRSb29tUmVwbHkQBxIUChBHZXRSb29tTGlzdFJlcGx5EAgS" + 
            "EwoPUGxheWVyRW50ZXJSb29tEAkqTgoPRW50ZXJSb29tUmVzdWx0EgYKAk9r" + 
            "EAESDQoJQWxyZWFkeUluEAISEQoNT3V0T2ZDYXBhY2l0eRADEhEKDVJvb21O" + 
            "b3RFeGlzdHMQBA==");
        pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
          descriptor = root;
          internal__static_world_messages_MsgPlayerEnterRoom__Descriptor = Descriptor.MessageTypes[0];
          internal__static_world_messages_MsgPlayerEnterRoom__FieldAccessorTable = 
              new pb::FieldAccess.FieldAccessorTable<global::world_messages.MsgPlayerEnterRoom, global::world_messages.MsgPlayerEnterRoom.Builder>(internal__static_world_messages_MsgPlayerEnterRoom__Descriptor,
                  new string[] { "RoomId", "PlayerId", });
          internal__static_world_messages_MsgEnterRoomReply__Descriptor = Descriptor.MessageTypes[1];
          internal__static_world_messages_MsgEnterRoomReply__FieldAccessorTable = 
              new pb::FieldAccess.FieldAccessorTable<global::world_messages.MsgEnterRoomReply, global::world_messages.MsgEnterRoomReply.Builder>(internal__static_world_messages_MsgEnterRoomReply__Descriptor,
                  new string[] { "Players", "Result", });
          internal__static_world_messages_WorldMessage__Descriptor = Descriptor.MessageTypes[2];
          internal__static_world_messages_WorldMessage__FieldAccessorTable = 
              new pb::FieldAccess.FieldAccessorTable<global::world_messages.WorldMessage, global::world_messages.WorldMessage.Builder>(internal__static_world_messages_WorldMessage__Descriptor,
                  new string[] { "Type", "PlayerId", "Buff", "MsgId", });
          internal__static_world_messages_Room__Descriptor = Descriptor.MessageTypes[3];
          internal__static_world_messages_Room__FieldAccessorTable = 
              new pb::FieldAccess.FieldAccessorTable<global::world_messages.Room, global::world_messages.Room.Builder>(internal__static_world_messages_Room__Descriptor,
                  new string[] { "Id", "PlayerCount", "Capacity", });
          internal__static_world_messages_ReplyMsg__Descriptor = Descriptor.MessageTypes[4];
          internal__static_world_messages_ReplyMsg__FieldAccessorTable = 
              new pb::FieldAccess.FieldAccessorTable<global::world_messages.ReplyMsg, global::world_messages.ReplyMsg.Builder>(internal__static_world_messages_ReplyMsg__Descriptor,
                  new string[] { "Type", "MsgId", "Buff", });
          internal__static_world_messages_MsgGetRoomListReply__Descriptor = Descriptor.MessageTypes[5];
          internal__static_world_messages_MsgGetRoomListReply__FieldAccessorTable = 
              new pb::FieldAccess.FieldAccessorTable<global::world_messages.MsgGetRoomListReply, global::world_messages.MsgGetRoomListReply.Builder>(internal__static_world_messages_MsgGetRoomListReply__Descriptor,
                  new string[] { "Rooms", });
          internal__static_world_messages_MsgCreateRoomReply__Descriptor = Descriptor.MessageTypes[6];
          internal__static_world_messages_MsgCreateRoomReply__FieldAccessorTable = 
              new pb::FieldAccess.FieldAccessorTable<global::world_messages.MsgCreateRoomReply, global::world_messages.MsgCreateRoomReply.Builder>(internal__static_world_messages_MsgCreateRoomReply__Descriptor,
                  new string[] { "ErrorCode", "Id", "Capacity", });
          return null;
        };
        pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
            new pbd::FileDescriptor[] {
            }, assigner);
      }
      #endregion
      
    }
  }
  #region Enums
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public enum MessageType {
    CreateRoom = 1,
    EnterRoom = 2,
    QuitRoom = 3,
    GetRoomList = 4,
    CreateRoomReply = 5,
    EnterRoomReply = 6,
    QuitRoomReply = 7,
    GetRoomListReply = 8,
    PlayerEnterRoom = 9,
  }
  
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public enum EnterRoomResult {
    Ok = 1,
    AlreadyIn = 2,
    OutOfCapacity = 3,
    RoomNotExists = 4,
  }
  
  #endregion
  
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public sealed partial class MsgPlayerEnterRoom : pb::GeneratedMessage<MsgPlayerEnterRoom, MsgPlayerEnterRoom.Builder> {
    private MsgPlayerEnterRoom() { }
    private static readonly MsgPlayerEnterRoom defaultInstance = new MsgPlayerEnterRoom().MakeReadOnly();
    private static readonly string[] _msgPlayerEnterRoomFieldNames = new string[] { "playerId", "roomId" };
    private static readonly uint[] _msgPlayerEnterRoomFieldTags = new uint[] { 18, 10 };
    public static MsgPlayerEnterRoom DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override MsgPlayerEnterRoom DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override MsgPlayerEnterRoom ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::world_messages.Proto.WorldMessage.internal__static_world_messages_MsgPlayerEnterRoom__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<MsgPlayerEnterRoom, MsgPlayerEnterRoom.Builder> InternalFieldAccessors {
      get { return global::world_messages.Proto.WorldMessage.internal__static_world_messages_MsgPlayerEnterRoom__FieldAccessorTable; }
    }
    
    public const int RoomIdFieldNumber = 1;
    private bool hasRoomId;
    private string roomId_ = "";
    public bool HasRoomId {
      get { return hasRoomId; }
    }
    public string RoomId {
      get { return roomId_; }
    }
    
    public const int PlayerIdFieldNumber = 2;
    private bool hasPlayerId;
    private string playerId_ = "";
    public bool HasPlayerId {
      get { return hasPlayerId; }
    }
    public string PlayerId {
      get { return playerId_; }
    }
    
    public override bool IsInitialized {
      get {
        if (!hasRoomId) return false;
        if (!hasPlayerId) return false;
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _msgPlayerEnterRoomFieldNames;
      if (hasRoomId) {
        output.WriteString(1, field_names[1], RoomId);
      }
      if (hasPlayerId) {
        output.WriteString(2, field_names[0], PlayerId);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (hasRoomId) {
          size += pb::CodedOutputStream.ComputeStringSize(1, RoomId);
        }
        if (hasPlayerId) {
          size += pb::CodedOutputStream.ComputeStringSize(2, PlayerId);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    public static MsgPlayerEnterRoom ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static MsgPlayerEnterRoom ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static MsgPlayerEnterRoom ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static MsgPlayerEnterRoom ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static MsgPlayerEnterRoom ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static MsgPlayerEnterRoom ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static MsgPlayerEnterRoom ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static MsgPlayerEnterRoom ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static MsgPlayerEnterRoom ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static MsgPlayerEnterRoom ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private MsgPlayerEnterRoom MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(MsgPlayerEnterRoom prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public sealed partial class Builder : pb::GeneratedBuilder<MsgPlayerEnterRoom, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(MsgPlayerEnterRoom cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private MsgPlayerEnterRoom result;
      
      private MsgPlayerEnterRoom PrepareBuilder() {
        if (resultIsReadOnly) {
          MsgPlayerEnterRoom original = result;
          result = new MsgPlayerEnterRoom();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override MsgPlayerEnterRoom MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::world_messages.MsgPlayerEnterRoom.Descriptor; }
      }
      
      public override MsgPlayerEnterRoom DefaultInstanceForType {
        get { return global::world_messages.MsgPlayerEnterRoom.DefaultInstance; }
      }
      
      public override MsgPlayerEnterRoom BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is MsgPlayerEnterRoom) {
          return MergeFrom((MsgPlayerEnterRoom) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(MsgPlayerEnterRoom other) {
        if (other == global::world_messages.MsgPlayerEnterRoom.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasRoomId) {
          RoomId = other.RoomId;
        }
        if (other.HasPlayerId) {
          PlayerId = other.PlayerId;
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_msgPlayerEnterRoomFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _msgPlayerEnterRoomFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 10: {
              result.hasRoomId = input.ReadString(ref result.roomId_);
              break;
            }
            case 18: {
              result.hasPlayerId = input.ReadString(ref result.playerId_);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasRoomId {
        get { return result.hasRoomId; }
      }
      public string RoomId {
        get { return result.RoomId; }
        set { SetRoomId(value); }
      }
      public Builder SetRoomId(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasRoomId = true;
        result.roomId_ = value;
        return this;
      }
      public Builder ClearRoomId() {
        PrepareBuilder();
        result.hasRoomId = false;
        result.roomId_ = "";
        return this;
      }
      
      public bool HasPlayerId {
        get { return result.hasPlayerId; }
      }
      public string PlayerId {
        get { return result.PlayerId; }
        set { SetPlayerId(value); }
      }
      public Builder SetPlayerId(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasPlayerId = true;
        result.playerId_ = value;
        return this;
      }
      public Builder ClearPlayerId() {
        PrepareBuilder();
        result.hasPlayerId = false;
        result.playerId_ = "";
        return this;
      }
    }
    static MsgPlayerEnterRoom() {
      object.ReferenceEquals(global::world_messages.Proto.WorldMessage.Descriptor, null);
    }
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public sealed partial class MsgEnterRoomReply : pb::GeneratedMessage<MsgEnterRoomReply, MsgEnterRoomReply.Builder> {
    private MsgEnterRoomReply() { }
    private static readonly MsgEnterRoomReply defaultInstance = new MsgEnterRoomReply().MakeReadOnly();
    private static readonly string[] _msgEnterRoomReplyFieldNames = new string[] { "players", "result" };
    private static readonly uint[] _msgEnterRoomReplyFieldTags = new uint[] { 10, 16 };
    public static MsgEnterRoomReply DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override MsgEnterRoomReply DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override MsgEnterRoomReply ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::world_messages.Proto.WorldMessage.internal__static_world_messages_MsgEnterRoomReply__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<MsgEnterRoomReply, MsgEnterRoomReply.Builder> InternalFieldAccessors {
      get { return global::world_messages.Proto.WorldMessage.internal__static_world_messages_MsgEnterRoomReply__FieldAccessorTable; }
    }
    
    public const int PlayersFieldNumber = 1;
    private pbc::PopsicleList<string> players_ = new pbc::PopsicleList<string>();
    public scg::IList<string> PlayersList {
      get { return pbc::Lists.AsReadOnly(players_); }
    }
    public int PlayersCount {
      get { return players_.Count; }
    }
    public string GetPlayers(int index) {
      return players_[index];
    }
    
    public const int ResultFieldNumber = 2;
    private bool hasResult;
    private global::world_messages.EnterRoomResult result_ = global::world_messages.EnterRoomResult.Ok;
    public bool HasResult {
      get { return hasResult; }
    }
    public global::world_messages.EnterRoomResult Result {
      get { return result_; }
    }
    
    public override bool IsInitialized {
      get {
        if (!hasResult) return false;
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _msgEnterRoomReplyFieldNames;
      if (players_.Count > 0) {
        output.WriteStringArray(1, field_names[0], players_);
      }
      if (hasResult) {
        output.WriteEnum(2, field_names[1], (int) Result, Result);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        {
          int dataSize = 0;
          foreach (string element in PlayersList) {
            dataSize += pb::CodedOutputStream.ComputeStringSizeNoTag(element);
          }
          size += dataSize;
          size += 1 * players_.Count;
        }
        if (hasResult) {
          size += pb::CodedOutputStream.ComputeEnumSize(2, (int) Result);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    public static MsgEnterRoomReply ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static MsgEnterRoomReply ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static MsgEnterRoomReply ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static MsgEnterRoomReply ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static MsgEnterRoomReply ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static MsgEnterRoomReply ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static MsgEnterRoomReply ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static MsgEnterRoomReply ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static MsgEnterRoomReply ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static MsgEnterRoomReply ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private MsgEnterRoomReply MakeReadOnly() {
      players_.MakeReadOnly();
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(MsgEnterRoomReply prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public sealed partial class Builder : pb::GeneratedBuilder<MsgEnterRoomReply, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(MsgEnterRoomReply cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private MsgEnterRoomReply result;
      
      private MsgEnterRoomReply PrepareBuilder() {
        if (resultIsReadOnly) {
          MsgEnterRoomReply original = result;
          result = new MsgEnterRoomReply();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override MsgEnterRoomReply MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::world_messages.MsgEnterRoomReply.Descriptor; }
      }
      
      public override MsgEnterRoomReply DefaultInstanceForType {
        get { return global::world_messages.MsgEnterRoomReply.DefaultInstance; }
      }
      
      public override MsgEnterRoomReply BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is MsgEnterRoomReply) {
          return MergeFrom((MsgEnterRoomReply) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(MsgEnterRoomReply other) {
        if (other == global::world_messages.MsgEnterRoomReply.DefaultInstance) return this;
        PrepareBuilder();
        if (other.players_.Count != 0) {
          result.players_.Add(other.players_);
        }
        if (other.HasResult) {
          Result = other.Result;
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_msgEnterRoomReplyFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _msgEnterRoomReplyFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 10: {
              input.ReadStringArray(tag, field_name, result.players_);
              break;
            }
            case 16: {
              object unknown;
              if(input.ReadEnum(ref result.result_, out unknown)) {
                result.hasResult = true;
              } else if(unknown is int) {
                if (unknownFields == null) {
                  unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
                }
                unknownFields.MergeVarintField(2, (ulong)(int)unknown);
              }
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public pbc::IPopsicleList<string> PlayersList {
        get { return PrepareBuilder().players_; }
      }
      public int PlayersCount {
        get { return result.PlayersCount; }
      }
      public string GetPlayers(int index) {
        return result.GetPlayers(index);
      }
      public Builder SetPlayers(int index, string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.players_[index] = value;
        return this;
      }
      public Builder AddPlayers(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.players_.Add(value);
        return this;
      }
      public Builder AddRangePlayers(scg::IEnumerable<string> values) {
        PrepareBuilder();
        result.players_.Add(values);
        return this;
      }
      public Builder ClearPlayers() {
        PrepareBuilder();
        result.players_.Clear();
        return this;
      }
      
      public bool HasResult {
       get { return result.hasResult; }
      }
      public global::world_messages.EnterRoomResult Result {
        get { return result.Result; }
        set { SetResult(value); }
      }
      public Builder SetResult(global::world_messages.EnterRoomResult value) {
        PrepareBuilder();
        result.hasResult = true;
        result.result_ = value;
        return this;
      }
      public Builder ClearResult() {
        PrepareBuilder();
        result.hasResult = false;
        result.result_ = global::world_messages.EnterRoomResult.Ok;
        return this;
      }
    }
    static MsgEnterRoomReply() {
      object.ReferenceEquals(global::world_messages.Proto.WorldMessage.Descriptor, null);
    }
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public sealed partial class WorldMessage : pb::GeneratedMessage<WorldMessage, WorldMessage.Builder> {
    private WorldMessage() { }
    private static readonly WorldMessage defaultInstance = new WorldMessage().MakeReadOnly();
    private static readonly string[] _worldMessageFieldNames = new string[] { "buff", "msgId", "playerId", "type" };
    private static readonly uint[] _worldMessageFieldTags = new uint[] { 26, 32, 18, 8 };
    public static WorldMessage DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override WorldMessage DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override WorldMessage ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::world_messages.Proto.WorldMessage.internal__static_world_messages_WorldMessage__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<WorldMessage, WorldMessage.Builder> InternalFieldAccessors {
      get { return global::world_messages.Proto.WorldMessage.internal__static_world_messages_WorldMessage__FieldAccessorTable; }
    }
    
    public const int TypeFieldNumber = 1;
    private bool hasType;
    private global::world_messages.MessageType type_ = global::world_messages.MessageType.CreateRoom;
    public bool HasType {
      get { return hasType; }
    }
    public global::world_messages.MessageType Type {
      get { return type_; }
    }
    
    public const int PlayerIdFieldNumber = 2;
    private bool hasPlayerId;
    private string playerId_ = "";
    public bool HasPlayerId {
      get { return hasPlayerId; }
    }
    public string PlayerId {
      get { return playerId_; }
    }
    
    public const int BuffFieldNumber = 3;
    private bool hasBuff;
    private pb::ByteString buff_ = pb::ByteString.Empty;
    public bool HasBuff {
      get { return hasBuff; }
    }
    public pb::ByteString Buff {
      get { return buff_; }
    }
    
    public const int MsgIdFieldNumber = 4;
    private bool hasMsgId;
    private int msgId_;
    public bool HasMsgId {
      get { return hasMsgId; }
    }
    public int MsgId {
      get { return msgId_; }
    }
    
    public override bool IsInitialized {
      get {
        if (!hasType) return false;
        if (!hasPlayerId) return false;
        if (!hasMsgId) return false;
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _worldMessageFieldNames;
      if (hasType) {
        output.WriteEnum(1, field_names[3], (int) Type, Type);
      }
      if (hasPlayerId) {
        output.WriteString(2, field_names[2], PlayerId);
      }
      if (hasBuff) {
        output.WriteBytes(3, field_names[0], Buff);
      }
      if (hasMsgId) {
        output.WriteInt32(4, field_names[1], MsgId);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (hasType) {
          size += pb::CodedOutputStream.ComputeEnumSize(1, (int) Type);
        }
        if (hasPlayerId) {
          size += pb::CodedOutputStream.ComputeStringSize(2, PlayerId);
        }
        if (hasBuff) {
          size += pb::CodedOutputStream.ComputeBytesSize(3, Buff);
        }
        if (hasMsgId) {
          size += pb::CodedOutputStream.ComputeInt32Size(4, MsgId);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    public static WorldMessage ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static WorldMessage ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static WorldMessage ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static WorldMessage ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static WorldMessage ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static WorldMessage ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static WorldMessage ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static WorldMessage ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static WorldMessage ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static WorldMessage ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private WorldMessage MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(WorldMessage prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public sealed partial class Builder : pb::GeneratedBuilder<WorldMessage, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(WorldMessage cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private WorldMessage result;
      
      private WorldMessage PrepareBuilder() {
        if (resultIsReadOnly) {
          WorldMessage original = result;
          result = new WorldMessage();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override WorldMessage MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::world_messages.WorldMessage.Descriptor; }
      }
      
      public override WorldMessage DefaultInstanceForType {
        get { return global::world_messages.WorldMessage.DefaultInstance; }
      }
      
      public override WorldMessage BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is WorldMessage) {
          return MergeFrom((WorldMessage) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(WorldMessage other) {
        if (other == global::world_messages.WorldMessage.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasType) {
          Type = other.Type;
        }
        if (other.HasPlayerId) {
          PlayerId = other.PlayerId;
        }
        if (other.HasBuff) {
          Buff = other.Buff;
        }
        if (other.HasMsgId) {
          MsgId = other.MsgId;
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_worldMessageFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _worldMessageFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 8: {
              object unknown;
              if(input.ReadEnum(ref result.type_, out unknown)) {
                result.hasType = true;
              } else if(unknown is int) {
                if (unknownFields == null) {
                  unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
                }
                unknownFields.MergeVarintField(1, (ulong)(int)unknown);
              }
              break;
            }
            case 18: {
              result.hasPlayerId = input.ReadString(ref result.playerId_);
              break;
            }
            case 26: {
              result.hasBuff = input.ReadBytes(ref result.buff_);
              break;
            }
            case 32: {
              result.hasMsgId = input.ReadInt32(ref result.msgId_);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasType {
       get { return result.hasType; }
      }
      public global::world_messages.MessageType Type {
        get { return result.Type; }
        set { SetType(value); }
      }
      public Builder SetType(global::world_messages.MessageType value) {
        PrepareBuilder();
        result.hasType = true;
        result.type_ = value;
        return this;
      }
      public Builder ClearType() {
        PrepareBuilder();
        result.hasType = false;
        result.type_ = global::world_messages.MessageType.CreateRoom;
        return this;
      }
      
      public bool HasPlayerId {
        get { return result.hasPlayerId; }
      }
      public string PlayerId {
        get { return result.PlayerId; }
        set { SetPlayerId(value); }
      }
      public Builder SetPlayerId(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasPlayerId = true;
        result.playerId_ = value;
        return this;
      }
      public Builder ClearPlayerId() {
        PrepareBuilder();
        result.hasPlayerId = false;
        result.playerId_ = "";
        return this;
      }
      
      public bool HasBuff {
        get { return result.hasBuff; }
      }
      public pb::ByteString Buff {
        get { return result.Buff; }
        set { SetBuff(value); }
      }
      public Builder SetBuff(pb::ByteString value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasBuff = true;
        result.buff_ = value;
        return this;
      }
      public Builder ClearBuff() {
        PrepareBuilder();
        result.hasBuff = false;
        result.buff_ = pb::ByteString.Empty;
        return this;
      }
      
      public bool HasMsgId {
        get { return result.hasMsgId; }
      }
      public int MsgId {
        get { return result.MsgId; }
        set { SetMsgId(value); }
      }
      public Builder SetMsgId(int value) {
        PrepareBuilder();
        result.hasMsgId = true;
        result.msgId_ = value;
        return this;
      }
      public Builder ClearMsgId() {
        PrepareBuilder();
        result.hasMsgId = false;
        result.msgId_ = 0;
        return this;
      }
    }
    static WorldMessage() {
      object.ReferenceEquals(global::world_messages.Proto.WorldMessage.Descriptor, null);
    }
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public sealed partial class Room : pb::GeneratedMessage<Room, Room.Builder> {
    private Room() { }
    private static readonly Room defaultInstance = new Room().MakeReadOnly();
    private static readonly string[] _roomFieldNames = new string[] { "capacity", "id", "playerCount" };
    private static readonly uint[] _roomFieldTags = new uint[] { 24, 10, 16 };
    public static Room DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override Room DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override Room ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::world_messages.Proto.WorldMessage.internal__static_world_messages_Room__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<Room, Room.Builder> InternalFieldAccessors {
      get { return global::world_messages.Proto.WorldMessage.internal__static_world_messages_Room__FieldAccessorTable; }
    }
    
    public const int IdFieldNumber = 1;
    private bool hasId;
    private string id_ = "";
    public bool HasId {
      get { return hasId; }
    }
    public string Id {
      get { return id_; }
    }
    
    public const int PlayerCountFieldNumber = 2;
    private bool hasPlayerCount;
    private int playerCount_;
    public bool HasPlayerCount {
      get { return hasPlayerCount; }
    }
    public int PlayerCount {
      get { return playerCount_; }
    }
    
    public const int CapacityFieldNumber = 3;
    private bool hasCapacity;
    private int capacity_;
    public bool HasCapacity {
      get { return hasCapacity; }
    }
    public int Capacity {
      get { return capacity_; }
    }
    
    public override bool IsInitialized {
      get {
        if (!hasId) return false;
        if (!hasPlayerCount) return false;
        if (!hasCapacity) return false;
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _roomFieldNames;
      if (hasId) {
        output.WriteString(1, field_names[1], Id);
      }
      if (hasPlayerCount) {
        output.WriteInt32(2, field_names[2], PlayerCount);
      }
      if (hasCapacity) {
        output.WriteInt32(3, field_names[0], Capacity);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (hasId) {
          size += pb::CodedOutputStream.ComputeStringSize(1, Id);
        }
        if (hasPlayerCount) {
          size += pb::CodedOutputStream.ComputeInt32Size(2, PlayerCount);
        }
        if (hasCapacity) {
          size += pb::CodedOutputStream.ComputeInt32Size(3, Capacity);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    public static Room ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static Room ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static Room ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static Room ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static Room ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static Room ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static Room ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static Room ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static Room ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static Room ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private Room MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(Room prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public sealed partial class Builder : pb::GeneratedBuilder<Room, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(Room cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private Room result;
      
      private Room PrepareBuilder() {
        if (resultIsReadOnly) {
          Room original = result;
          result = new Room();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override Room MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::world_messages.Room.Descriptor; }
      }
      
      public override Room DefaultInstanceForType {
        get { return global::world_messages.Room.DefaultInstance; }
      }
      
      public override Room BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is Room) {
          return MergeFrom((Room) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(Room other) {
        if (other == global::world_messages.Room.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasId) {
          Id = other.Id;
        }
        if (other.HasPlayerCount) {
          PlayerCount = other.PlayerCount;
        }
        if (other.HasCapacity) {
          Capacity = other.Capacity;
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_roomFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _roomFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 10: {
              result.hasId = input.ReadString(ref result.id_);
              break;
            }
            case 16: {
              result.hasPlayerCount = input.ReadInt32(ref result.playerCount_);
              break;
            }
            case 24: {
              result.hasCapacity = input.ReadInt32(ref result.capacity_);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasId {
        get { return result.hasId; }
      }
      public string Id {
        get { return result.Id; }
        set { SetId(value); }
      }
      public Builder SetId(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder ClearId() {
        PrepareBuilder();
        result.hasId = false;
        result.id_ = "";
        return this;
      }
      
      public bool HasPlayerCount {
        get { return result.hasPlayerCount; }
      }
      public int PlayerCount {
        get { return result.PlayerCount; }
        set { SetPlayerCount(value); }
      }
      public Builder SetPlayerCount(int value) {
        PrepareBuilder();
        result.hasPlayerCount = true;
        result.playerCount_ = value;
        return this;
      }
      public Builder ClearPlayerCount() {
        PrepareBuilder();
        result.hasPlayerCount = false;
        result.playerCount_ = 0;
        return this;
      }
      
      public bool HasCapacity {
        get { return result.hasCapacity; }
      }
      public int Capacity {
        get { return result.Capacity; }
        set { SetCapacity(value); }
      }
      public Builder SetCapacity(int value) {
        PrepareBuilder();
        result.hasCapacity = true;
        result.capacity_ = value;
        return this;
      }
      public Builder ClearCapacity() {
        PrepareBuilder();
        result.hasCapacity = false;
        result.capacity_ = 0;
        return this;
      }
    }
    static Room() {
      object.ReferenceEquals(global::world_messages.Proto.WorldMessage.Descriptor, null);
    }
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public sealed partial class ReplyMsg : pb::GeneratedMessage<ReplyMsg, ReplyMsg.Builder> {
    private ReplyMsg() { }
    private static readonly ReplyMsg defaultInstance = new ReplyMsg().MakeReadOnly();
    private static readonly string[] _replyMsgFieldNames = new string[] { "buff", "msgId", "type" };
    private static readonly uint[] _replyMsgFieldTags = new uint[] { 26, 16, 8 };
    public static ReplyMsg DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override ReplyMsg DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override ReplyMsg ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::world_messages.Proto.WorldMessage.internal__static_world_messages_ReplyMsg__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<ReplyMsg, ReplyMsg.Builder> InternalFieldAccessors {
      get { return global::world_messages.Proto.WorldMessage.internal__static_world_messages_ReplyMsg__FieldAccessorTable; }
    }
    
    public const int TypeFieldNumber = 1;
    private bool hasType;
    private global::world_messages.MessageType type_ = global::world_messages.MessageType.CreateRoom;
    public bool HasType {
      get { return hasType; }
    }
    public global::world_messages.MessageType Type {
      get { return type_; }
    }
    
    public const int MsgIdFieldNumber = 2;
    private bool hasMsgId;
    private int msgId_;
    public bool HasMsgId {
      get { return hasMsgId; }
    }
    public int MsgId {
      get { return msgId_; }
    }
    
    public const int BuffFieldNumber = 3;
    private bool hasBuff;
    private pb::ByteString buff_ = pb::ByteString.Empty;
    public bool HasBuff {
      get { return hasBuff; }
    }
    public pb::ByteString Buff {
      get { return buff_; }
    }
    
    public override bool IsInitialized {
      get {
        if (!hasType) return false;
        if (!hasMsgId) return false;
        if (!hasBuff) return false;
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _replyMsgFieldNames;
      if (hasType) {
        output.WriteEnum(1, field_names[2], (int) Type, Type);
      }
      if (hasMsgId) {
        output.WriteInt32(2, field_names[1], MsgId);
      }
      if (hasBuff) {
        output.WriteBytes(3, field_names[0], Buff);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (hasType) {
          size += pb::CodedOutputStream.ComputeEnumSize(1, (int) Type);
        }
        if (hasMsgId) {
          size += pb::CodedOutputStream.ComputeInt32Size(2, MsgId);
        }
        if (hasBuff) {
          size += pb::CodedOutputStream.ComputeBytesSize(3, Buff);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    public static ReplyMsg ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static ReplyMsg ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static ReplyMsg ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static ReplyMsg ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static ReplyMsg ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static ReplyMsg ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static ReplyMsg ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static ReplyMsg ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static ReplyMsg ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static ReplyMsg ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private ReplyMsg MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(ReplyMsg prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public sealed partial class Builder : pb::GeneratedBuilder<ReplyMsg, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(ReplyMsg cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private ReplyMsg result;
      
      private ReplyMsg PrepareBuilder() {
        if (resultIsReadOnly) {
          ReplyMsg original = result;
          result = new ReplyMsg();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override ReplyMsg MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::world_messages.ReplyMsg.Descriptor; }
      }
      
      public override ReplyMsg DefaultInstanceForType {
        get { return global::world_messages.ReplyMsg.DefaultInstance; }
      }
      
      public override ReplyMsg BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is ReplyMsg) {
          return MergeFrom((ReplyMsg) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(ReplyMsg other) {
        if (other == global::world_messages.ReplyMsg.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasType) {
          Type = other.Type;
        }
        if (other.HasMsgId) {
          MsgId = other.MsgId;
        }
        if (other.HasBuff) {
          Buff = other.Buff;
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_replyMsgFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _replyMsgFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 8: {
              object unknown;
              if(input.ReadEnum(ref result.type_, out unknown)) {
                result.hasType = true;
              } else if(unknown is int) {
                if (unknownFields == null) {
                  unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
                }
                unknownFields.MergeVarintField(1, (ulong)(int)unknown);
              }
              break;
            }
            case 16: {
              result.hasMsgId = input.ReadInt32(ref result.msgId_);
              break;
            }
            case 26: {
              result.hasBuff = input.ReadBytes(ref result.buff_);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasType {
       get { return result.hasType; }
      }
      public global::world_messages.MessageType Type {
        get { return result.Type; }
        set { SetType(value); }
      }
      public Builder SetType(global::world_messages.MessageType value) {
        PrepareBuilder();
        result.hasType = true;
        result.type_ = value;
        return this;
      }
      public Builder ClearType() {
        PrepareBuilder();
        result.hasType = false;
        result.type_ = global::world_messages.MessageType.CreateRoom;
        return this;
      }
      
      public bool HasMsgId {
        get { return result.hasMsgId; }
      }
      public int MsgId {
        get { return result.MsgId; }
        set { SetMsgId(value); }
      }
      public Builder SetMsgId(int value) {
        PrepareBuilder();
        result.hasMsgId = true;
        result.msgId_ = value;
        return this;
      }
      public Builder ClearMsgId() {
        PrepareBuilder();
        result.hasMsgId = false;
        result.msgId_ = 0;
        return this;
      }
      
      public bool HasBuff {
        get { return result.hasBuff; }
      }
      public pb::ByteString Buff {
        get { return result.Buff; }
        set { SetBuff(value); }
      }
      public Builder SetBuff(pb::ByteString value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasBuff = true;
        result.buff_ = value;
        return this;
      }
      public Builder ClearBuff() {
        PrepareBuilder();
        result.hasBuff = false;
        result.buff_ = pb::ByteString.Empty;
        return this;
      }
    }
    static ReplyMsg() {
      object.ReferenceEquals(global::world_messages.Proto.WorldMessage.Descriptor, null);
    }
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public sealed partial class MsgGetRoomListReply : pb::GeneratedMessage<MsgGetRoomListReply, MsgGetRoomListReply.Builder> {
    private MsgGetRoomListReply() { }
    private static readonly MsgGetRoomListReply defaultInstance = new MsgGetRoomListReply().MakeReadOnly();
    private static readonly string[] _msgGetRoomListReplyFieldNames = new string[] { "rooms" };
    private static readonly uint[] _msgGetRoomListReplyFieldTags = new uint[] { 10 };
    public static MsgGetRoomListReply DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override MsgGetRoomListReply DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override MsgGetRoomListReply ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::world_messages.Proto.WorldMessage.internal__static_world_messages_MsgGetRoomListReply__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<MsgGetRoomListReply, MsgGetRoomListReply.Builder> InternalFieldAccessors {
      get { return global::world_messages.Proto.WorldMessage.internal__static_world_messages_MsgGetRoomListReply__FieldAccessorTable; }
    }
    
    public const int RoomsFieldNumber = 1;
    private pbc::PopsicleList<global::world_messages.Room> rooms_ = new pbc::PopsicleList<global::world_messages.Room>();
    public scg::IList<global::world_messages.Room> RoomsList {
      get { return rooms_; }
    }
    public int RoomsCount {
      get { return rooms_.Count; }
    }
    public global::world_messages.Room GetRooms(int index) {
      return rooms_[index];
    }
    
    public override bool IsInitialized {
      get {
        foreach (global::world_messages.Room element in RoomsList) {
          if (!element.IsInitialized) return false;
        }
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _msgGetRoomListReplyFieldNames;
      if (rooms_.Count > 0) {
        output.WriteMessageArray(1, field_names[0], rooms_);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        foreach (global::world_messages.Room element in RoomsList) {
          size += pb::CodedOutputStream.ComputeMessageSize(1, element);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    public static MsgGetRoomListReply ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static MsgGetRoomListReply ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static MsgGetRoomListReply ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static MsgGetRoomListReply ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static MsgGetRoomListReply ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static MsgGetRoomListReply ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static MsgGetRoomListReply ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static MsgGetRoomListReply ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static MsgGetRoomListReply ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static MsgGetRoomListReply ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private MsgGetRoomListReply MakeReadOnly() {
      rooms_.MakeReadOnly();
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(MsgGetRoomListReply prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public sealed partial class Builder : pb::GeneratedBuilder<MsgGetRoomListReply, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(MsgGetRoomListReply cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private MsgGetRoomListReply result;
      
      private MsgGetRoomListReply PrepareBuilder() {
        if (resultIsReadOnly) {
          MsgGetRoomListReply original = result;
          result = new MsgGetRoomListReply();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override MsgGetRoomListReply MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::world_messages.MsgGetRoomListReply.Descriptor; }
      }
      
      public override MsgGetRoomListReply DefaultInstanceForType {
        get { return global::world_messages.MsgGetRoomListReply.DefaultInstance; }
      }
      
      public override MsgGetRoomListReply BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is MsgGetRoomListReply) {
          return MergeFrom((MsgGetRoomListReply) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(MsgGetRoomListReply other) {
        if (other == global::world_messages.MsgGetRoomListReply.DefaultInstance) return this;
        PrepareBuilder();
        if (other.rooms_.Count != 0) {
          result.rooms_.Add(other.rooms_);
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_msgGetRoomListReplyFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _msgGetRoomListReplyFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 10: {
              input.ReadMessageArray(tag, field_name, result.rooms_, global::world_messages.Room.DefaultInstance, extensionRegistry);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public pbc::IPopsicleList<global::world_messages.Room> RoomsList {
        get { return PrepareBuilder().rooms_; }
      }
      public int RoomsCount {
        get { return result.RoomsCount; }
      }
      public global::world_messages.Room GetRooms(int index) {
        return result.GetRooms(index);
      }
      public Builder SetRooms(int index, global::world_messages.Room value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.rooms_[index] = value;
        return this;
      }
      public Builder SetRooms(int index, global::world_messages.Room.Builder builderForValue) {
        pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
        PrepareBuilder();
        result.rooms_[index] = builderForValue.Build();
        return this;
      }
      public Builder AddRooms(global::world_messages.Room value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.rooms_.Add(value);
        return this;
      }
      public Builder AddRooms(global::world_messages.Room.Builder builderForValue) {
        pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
        PrepareBuilder();
        result.rooms_.Add(builderForValue.Build());
        return this;
      }
      public Builder AddRangeRooms(scg::IEnumerable<global::world_messages.Room> values) {
        PrepareBuilder();
        result.rooms_.Add(values);
        return this;
      }
      public Builder ClearRooms() {
        PrepareBuilder();
        result.rooms_.Clear();
        return this;
      }
    }
    static MsgGetRoomListReply() {
      object.ReferenceEquals(global::world_messages.Proto.WorldMessage.Descriptor, null);
    }
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public sealed partial class MsgCreateRoomReply : pb::GeneratedMessage<MsgCreateRoomReply, MsgCreateRoomReply.Builder> {
    private MsgCreateRoomReply() { }
    private static readonly MsgCreateRoomReply defaultInstance = new MsgCreateRoomReply().MakeReadOnly();
    private static readonly string[] _msgCreateRoomReplyFieldNames = new string[] { "capacity", "errorCode", "id" };
    private static readonly uint[] _msgCreateRoomReplyFieldTags = new uint[] { 24, 8, 18 };
    public static MsgCreateRoomReply DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override MsgCreateRoomReply DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override MsgCreateRoomReply ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::world_messages.Proto.WorldMessage.internal__static_world_messages_MsgCreateRoomReply__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<MsgCreateRoomReply, MsgCreateRoomReply.Builder> InternalFieldAccessors {
      get { return global::world_messages.Proto.WorldMessage.internal__static_world_messages_MsgCreateRoomReply__FieldAccessorTable; }
    }
    
    public const int ErrorCodeFieldNumber = 1;
    private bool hasErrorCode;
    private int errorCode_;
    public bool HasErrorCode {
      get { return hasErrorCode; }
    }
    public int ErrorCode {
      get { return errorCode_; }
    }
    
    public const int IdFieldNumber = 2;
    private bool hasId;
    private string id_ = "";
    public bool HasId {
      get { return hasId; }
    }
    public string Id {
      get { return id_; }
    }
    
    public const int CapacityFieldNumber = 3;
    private bool hasCapacity;
    private int capacity_;
    public bool HasCapacity {
      get { return hasCapacity; }
    }
    public int Capacity {
      get { return capacity_; }
    }
    
    public override bool IsInitialized {
      get {
        if (!hasErrorCode) return false;
        if (!hasId) return false;
        if (!hasCapacity) return false;
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _msgCreateRoomReplyFieldNames;
      if (hasErrorCode) {
        output.WriteInt32(1, field_names[1], ErrorCode);
      }
      if (hasId) {
        output.WriteString(2, field_names[2], Id);
      }
      if (hasCapacity) {
        output.WriteInt32(3, field_names[0], Capacity);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (hasErrorCode) {
          size += pb::CodedOutputStream.ComputeInt32Size(1, ErrorCode);
        }
        if (hasId) {
          size += pb::CodedOutputStream.ComputeStringSize(2, Id);
        }
        if (hasCapacity) {
          size += pb::CodedOutputStream.ComputeInt32Size(3, Capacity);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    public static MsgCreateRoomReply ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static MsgCreateRoomReply ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static MsgCreateRoomReply ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static MsgCreateRoomReply ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static MsgCreateRoomReply ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static MsgCreateRoomReply ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static MsgCreateRoomReply ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static MsgCreateRoomReply ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static MsgCreateRoomReply ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static MsgCreateRoomReply ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private MsgCreateRoomReply MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(MsgCreateRoomReply prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public sealed partial class Builder : pb::GeneratedBuilder<MsgCreateRoomReply, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(MsgCreateRoomReply cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private MsgCreateRoomReply result;
      
      private MsgCreateRoomReply PrepareBuilder() {
        if (resultIsReadOnly) {
          MsgCreateRoomReply original = result;
          result = new MsgCreateRoomReply();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override MsgCreateRoomReply MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::world_messages.MsgCreateRoomReply.Descriptor; }
      }
      
      public override MsgCreateRoomReply DefaultInstanceForType {
        get { return global::world_messages.MsgCreateRoomReply.DefaultInstance; }
      }
      
      public override MsgCreateRoomReply BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is MsgCreateRoomReply) {
          return MergeFrom((MsgCreateRoomReply) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(MsgCreateRoomReply other) {
        if (other == global::world_messages.MsgCreateRoomReply.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasErrorCode) {
          ErrorCode = other.ErrorCode;
        }
        if (other.HasId) {
          Id = other.Id;
        }
        if (other.HasCapacity) {
          Capacity = other.Capacity;
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_msgCreateRoomReplyFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _msgCreateRoomReplyFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 8: {
              result.hasErrorCode = input.ReadInt32(ref result.errorCode_);
              break;
            }
            case 18: {
              result.hasId = input.ReadString(ref result.id_);
              break;
            }
            case 24: {
              result.hasCapacity = input.ReadInt32(ref result.capacity_);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasErrorCode {
        get { return result.hasErrorCode; }
      }
      public int ErrorCode {
        get { return result.ErrorCode; }
        set { SetErrorCode(value); }
      }
      public Builder SetErrorCode(int value) {
        PrepareBuilder();
        result.hasErrorCode = true;
        result.errorCode_ = value;
        return this;
      }
      public Builder ClearErrorCode() {
        PrepareBuilder();
        result.hasErrorCode = false;
        result.errorCode_ = 0;
        return this;
      }
      
      public bool HasId {
        get { return result.hasId; }
      }
      public string Id {
        get { return result.Id; }
        set { SetId(value); }
      }
      public Builder SetId(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder ClearId() {
        PrepareBuilder();
        result.hasId = false;
        result.id_ = "";
        return this;
      }
      
      public bool HasCapacity {
        get { return result.hasCapacity; }
      }
      public int Capacity {
        get { return result.Capacity; }
        set { SetCapacity(value); }
      }
      public Builder SetCapacity(int value) {
        PrepareBuilder();
        result.hasCapacity = true;
        result.capacity_ = value;
        return this;
      }
      public Builder ClearCapacity() {
        PrepareBuilder();
        result.hasCapacity = false;
        result.capacity_ = 0;
        return this;
      }
    }
    static MsgCreateRoomReply() {
      object.ReferenceEquals(global::world_messages.Proto.WorldMessage.Descriptor, null);
    }
  }
  
  #endregion
  
}

#endregion Designer generated code
